// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_PCC.Models
{
    public partial class GetUserLogInResult
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
