// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class HBuffHerd
{
    public int Id { get; set; }

    public string HerdName { get; set; }

    public string HerdCode { get; set; }

    public int HerdSize { get; set; }

    public string BBuffCode { get; set; }

    public string FCode { get; set; }

    public string HTypeCode { get; set; }

    public string FeedCode { get; set; }

    public string FarmManager { get; set; }

    public string FarmAddress { get; set; }

    public string Owner { get; set; }

    public string Address { get; set; }

    public string TelNo { get; set; }

    public string MNo { get; set; }

    public string Email { get; set; }

    public int Status { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime DateUpdated { get; set; }

    public bool DeleteFlag { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? DateDeleted { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DateRestored { get; set; }

    public string RestoredBy { get; set; }
    public string? OrganizationName { get; set; }
    public string? Center { get; set; }
}